### ISSUE TITLE
postinst missing ENV var

### ISSUE THREAD

**Issue by stylesuxx** [fpv-wtf/wtfos-modloader#1]
The post installation script tries to enable the service via dinit. dinit needs the `HOME` env variable to be set to `/data` otherwise it will complain that it's not able to find the socket:

```
dinitctl: connecting to socket /opt/root/.dinitctl: No such file or directory
Collected errors:
* pkg_run_script: package "tweak-enable-debug-menu" postinst script returned status 1.
* opkg_configure: tweak-enable-debug-menu.postinst returned 1.
Installing tweak-enable-debug-menu (0.1.3) to root...
Downloading http://repo.fpv.wtf/pigeon/tweak-enable-debug-menu_0.1.3_armv7-3.2.ipk
Configuring tweak-enable-debug-menu.
```

Basically https://github.com/fpv-wtf/wtfos-modloader/blob/2000b2b8d037e1d67de1f74ffb6a4b79208db805/tweak-enable-debug-menu/ipk/control/postinst#L5 should read:
```sh
HOME=/data /opt/sbin/dinitctl -u enable tweak-enable-debug-menu
```

I checked the dinit source because I thought that I could set this during compile time, but the `SYSCONTROLSOCKET` is only used when NOT running in user mode. Relevant code is here:

https://github.com/davmac314/dinit/blob/b1cfd8a38d7aa7b9ea951563b21ccff4d29ec213/src/includes/dinit-client.h#L279

Maybe you have a better idea for not needing to set the `HOME` env var before each interaction with `dinitctl -u`.

**Comment by j005u** [comment]
Have essentially all commands to adb from configurator do `. /etc/mkshrc && actual_command`, that way you get rid of having to set a bunch of other vars too?

Alternatively, open "an interactive shell" in the background for running commands rather than doing one shot commands?

**Comment by stylesuxx** [comment]
Yes, sourcing `mkshrc` is actually a good idea. Closing this open.
