### ISSUE TITLE
How to call AV-IN on the main menu page!?

### ISSUE THREAD

**Issue by mickeyboss123** [fpv-wtf/wtfos-modloader#9]
How to call AV-IN on the main menu page!?
![Inkeddji-fpv-system1](https://github.com/fpv-wtf/wtfos-modloader/assets/1274528/2c1e8c3d-ecce-47ec-af4e-a2ae8da2ef96)

I tried adding in racing_top_menu.xml
<menuitem
widget.icon.image.name="setting/default.png"
widget.icon.selimage.name="setting/active.png"
widget.menubutton.data = "Av-In"
widget.title.text="Av-In"
/>

But it doesn't work after click

**Comment by j005u** [comment]
There is no simple way of achieving this since the click handlers are on each separate submenu. The code for launching av-in is on the settings menu class.

You can see how I hook the menu to execute custom commands here: https://github.com/fpv-wtf/wtfos-modloader/blob/main/menu_hook/jni/menu_hook.c#L71

You would need to extend this somehow to call the relavant code to activate av-in from `GlassRacingSettingsMenu::onMenuReturnImpl(GlassRacingSettingsMenu *this,MMSWidget *param_1)`.

This is doable, but not trivial.

**Comment by mickeyboss123** [comment]
Thank you for your help
it's very important to me 

☆☆☆What system and software should be used to compile??
vs code or Android Studio  ^^"

**Comment by j005u** [comment]
We use android ndk-23. Please take a look at the linked menu_hook build setup.

Also I should add that the existing menu_hook is obviously extremely hacky. The reason for having gone this route is that the relavant libraries are all C++ and they are quite difficulty to interact with using the build setup we presently have.

**Comment by mickeyboss123** [comment]
Thank you, I know this part is difficult, I'm working on it, hope it helps in the future


I use the Command Prompt in windows to compile (ndk-build)

The start.sh in the menu_hook file directory cannot be executed smoothly, I can only enter the command manually

After the compilation is completed, two libmenu_hook.so are generated, which makes me feel very confused
menu_hook\libs\armeabi-v7a\libmenu_hook.so
menu_hook\obj\local\armeabi-v7a\libmenu_hook.so
The two files are different sizes, so I should use which one

The command line of start.sh is !?
adb shell "LD_PRELOAD=\"/tmp/libmenu_hook.so /opt/lib/libmodloader_final.so\" dji_gls_wm150_original -g"


Follow the instructions of wtfos-modloader

Install a mod through package management or place your shared library into /opt/etc/preload.d/lib${your_mod_name}.so.

Then, to enable your_mod_name on the DIY GUI process run the following:

modmanager enable diy_glasses your_mod_name

**Comment by j005u** [comment]
Closing as emulamer found a _much_ simpler way to achieve this: https://github.com/emulamer/avin-startup

His package is now available on the official repo.
